fastboot erase boot_ab || @echo "Erase boot error"
fastboot erase expdb || @echo "Erase expdb error"
fastboot erase metadata || @echo "Erase metadata error"
fastboot flash preloader_ab images\preloader_chopin.bin  || @echo "Flash preloader error"
fastboot flash lk_ab        images\lk.img         || @echo "Flash lk        error"
fastboot flash dpm_ab     images\dpm.img        || @echo "Flash dpm       error"
fastboot flash tee_ab      images\tee.img        || @echo "Flash tee_a      error"
fastboot flash mitee_ab    images\mitee.img     	|| @echo "Flash mitee error"
fastboot flash sspm_ab    images\sspm.img       || @echo "Flash sspm_a    error"
fastboot flash gz_ab       images\gz.img         || @echo "Flash gz_a       error"
fastboot flash scp_ab      images\scp.img        || @echo "Flash scp_a      error"
fastboot flash logo      images\logo.bin       || @echo "Flash logo      error"
fastboot flash dtbo_ab      images\dtbo.img       || @echo "Flash dtbo      error"
fastboot flash spmfw_ab     images\spmfw.img      || @echo "Flash spmfw     error"
fastboot flash mcupm_ab   images\mcupm.img      || @echo "Flash mcupm     error"
fastboot flash pi_img_ab    images\pi_img.img     || @echo "Flash pi_img    error"
::fastboot flash oem_misc1 images\oem_misc1.img  || @echo "Flash oem_misc1 error"
fastboot flash md1img_ab    images\md1img.img     || @echo "Flash md1img    error"
fastboot flash cam_vpu1_ab  images\cam_vpu1.img   || @echo "Flash cam_vpu1  error"
fastboot flash cam_vpu2_ab  images\cam_vpu2.img   || @echo "Flash cam_vpu2  error"
fastboot flash cam_vpu3_ab  images\cam_vpu3.img   || @echo "Flash cam_vpu3  error"
fastboot flash audio_dsp_ab images\audio_dsp.img  || @echo "Flash audio_dsp error"

fastboot flash super            images\super.img             || @echo "Flash super    error"
fastboot flash rescue           images\rescue.img            || @echo "Flash rescue   error"
::fastboot flash cache            images\cache.img             || @echo "Flash cache    error"
::fastboot flash recovery         images\recovery.img          || @echo "Flash recovery error"
::fastboot flash cust             images\cust.img              || @echo "Flash cust     error"
fastboot flash vbmeta_ab           images\vbmeta.img            || @echo "Flash vbmeta   error"
fastboot flash vbmeta_system_ab    images\vbmeta_system.img     || @echo "Flash vbmeta_system   error"
fastboot flash vbmeta_vendor_ab    images\vbmeta_vendor.img     || @echo "Flash vbmeta_vendor   error"
fastboot flash cust         		images\cust.img        		|| @echo "Flash cust 			error"
fastboot flash userdata         images\userdata.img          || @echo "Flash userdata error"
fastboot flash boot_ab             images\boot.img              || @echo "Flash boot     error"
fastboot oem cdms
fastboot set_active a  || @echo "set_active a error"
fastboot reboot || @echo "Reboot error"

